[package]
name = "player"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.1.6", features = ["derive"] }
cpal = "0.15.0"
symphonia = { version = "0.5", features = ["mp3", "aac", "isomp4"] }
